travis:
  secure:
    BINSTAR_TOKEN: oPLmfPTk8XjTfVyFXPVcmeSUPkpY03Qx5tvAy+isZQRS8hpPGr0RkoklUOAH/6vDJxqzoe5T1iyYNigAYKvqbB9Egv2XGKg0RpC6NrMzD0Z4hWHGmqXfZ/be5PkYCDTo7V0ngtpS0tRVjtGj99outbHkGD0c87M6Fvps3pzJEpqlGozNaTfhnrxA6odq8Yo1Qii8VwWte0uRWxG0Zhr4AwUsx812nXJcpLJoTPo2YC2ndpmjHnF6QtGL1Z/N3KSSLi8tzCchFh4dpw5gYNXn8wSprfAC0NMBAG7ltH5cxG2hfeU/oBHKS1XPNwT64c4LG4/wUQh4ZvAbgGRcqGwVZaIb8YARcxDXdvPuW3UpYKz/W1mqHSxHF6oz1JRiqP/g2HnXKtlBi0yuV/HXwzMYdCMRa+3CvAcmzbECLcXNwRtVUl8kaMxZIvm7Qk7fyJ2QWgDv5HaDgspsDzkos5f1ZGfjoILNuuKW+rEalLErKmKE/ZaQi+IOQ3ggL1P/XrqWogN/AqNN1lFSFPLlVofjsFiZ/COFNvFLiU4Le+oKUdgE4/EGTcBZaqJyf4VIfAoO/OEW4uui43AiBFBWhi7bx+J5ERrxCgWPMS34K+0fj3T+PrYIo7UfKOtFq7pS3q4NNBdiZ3W/gALLHqEKbYFVYXKm7jm/RtcmgTiZNB67rCw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
