travis:
  secure:
    BINSTAR_TOKEN: iqOKXpBnVuYSWiZ6x1hZi8OqNsKpFMuzECNaMh560qtaa49dxplPpcZCzauqfT4qtlxZlVCbCsltQKB65oaZCgOuSkqCARcVBV8r5J/ZJf8qw7Y13WFGKNzHiMSJwSQP9vAbR1OLY17L1Ax9CbuYL/pAIfqaaD2STcUJPv2H9D48yGfVQ/ZmrmZP/a4z3Wm7jrxrAGJ+TTDH+CwYkD+M+0nhWd5OZ+8NqOv8NE0sw+tTdNRdQzDH8D9u5UulIpWjwqT1pR7ntKn7jO3G9E5WVQZBkKzKyr+C4/NcgEq+MIhl6qteNHKoAjI2xZamt3vmDrQMX8CfEjd/3cS2/dlTH56v53cX5MqrwprQ69lbOGc/CXaMF52HOxsCW5cbOFp6imYW7AUj/UATlbSzS/VCLiP7R7/KdL/P9TffLmiWrkKCbFxhh/1wOw82XCNKvIYV7DZa6A3ZUy4KhU+cyDd19LqWYCjL7pN0Qhl+Cx2M7p9Q3UaaydYCRJFFekCVBFlO/wRlurjNuRY0Bi2dMlys4vrIExGEbrm5KUr0YerhNG3VT8hwVeR7Pdi68UJODJbZxP4Kj6zTMeLaTQ8i8+nIndcJITFw6uBeE6mr6tdMkUGv3ifuqvlOfbYD/Ho1RBqoiI0gYNt4k21H5+a/wCHCEMwn8zPHEMj+3Yn0Fpnnbco=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
